backend:
  name: github
  repo: itachiRedhair/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: stuffIKnow
    label: Stuff I Know
    folder: stuffIKnow
    create: true
    fields:
      - { name: "name", label: "Stuff Name" }
