backend:
  name: github
  repo: itachiRedhair/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Content"
    name: "mainContent"
    files:
      - label: "Stuff I Know"
        name: "stuffIKnow"
        file: "content/stuffIKnow.md"
        fields:
          - { label: Title, name: title }
