backend:
  name: github
  repo: itachiRedhair/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Content"
    name: "mainContent"
    files:
      - label: "Name and Description"
        name: "nameNDesc"
        file: "content/name-and-description.md"
        fields:
          - { label: Name, name: name }
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: "Work"
        name: "Work"
        file: "content/work.md"
        fields:
          - { label: Work, name: work }
      - label: "Stuff"
        name: "stuff"
        file: "content/stuff.md"
        fields:
          - { label: "Stuff I Know", name: stuffIKnow, widget: "list" }
          - {
              label: "Stuff I Am Learning",
              name: stuffIAmLearning,
              widget: "list",
            }
      - label: "Experiments"
        name: "experiments"
        file: "content/experiments.md"
        fields:
          - label: "Experiments"
            name: experiments
            widget: "list"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Description, name: description, widget: string }
      - label: "Writings"
        name: "writings"
        file: "content/writings.md"
        fields:
          - label: "Writings"
            name: writings
            widget: "list"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Link, name: link, widget: string }