backend:
  name: github
  repo: itachiRedhair/portfolio

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Content"
    name: "mainContent"
    files:
      - label: "Name and Description"
        name: "name"
        file: "content/name-and-description.md"
        identifier_field: name
        fields:
          - { label: Name, name: name }
          - { label: Description, name: description }
